name: Rust Basic workflow

on:
 workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest

    # Linter checks first
    steps:
    - uses: actions/checkout@v3
    
    - name: Clippy
      run: cargo clippy -- -A clippy::too-many-arguments -D warnings
      
    - name: Formatting
      run: cargo fmt --all -- --check
      
    - name: Build
      run: cargo build
      
    - name: Tests
      run: cargo test
