name: Rust

on:
 workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest

    # Linter checks first
    steps:
    - uses: actions/checkout@v3
    - name: Test clippy
      run: cargo clippy -- -A clippy::too-many-arguments -D warnings
    - name: Test fmt
      run: cargo fmt --all -- --check
    - uses: actions/checkout@v3
    - name: Cargo build
      run: cargo build
    - name: Run tests
      run: cargo test
    
