name: Rust

on:
 workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest

    # Linter checks first
    steps:
    - name: Uphill
      run: cd ..
    - uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: --all -- --check
    - uses: actions-rs/cargo@v1
      with:       
          command: clippy
          args: -- -A clippy::too-many-arguments -D warnings

    - uses: actions/checkout@v3
    - name: Cargo build
      run: cargo build
    - name: Run tests
      run: cargo test
    
 
