name: Solana workflow

on:
 workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Linter:

    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2

    # Linter checks first
    steps:
    - uses: actions/checkout@v3
    
    - name: List rustup toolchains
      run: rustup toolchain list
    - name: Set default toolchain
      run: rustup default stable
    - name: Look into folder
      run: ls -lha
    - name: Build itself
      run: cargo build-bpf
      
