name: Solana workflow

on:
 workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Linter:

    runs-on: ubuntu-latest

    # Linter checks first
    steps:
    - uses: actions/checkout@v3
    
    - name: Formatting
      run: cargo fmt --all -- --check
    
    - name: Clippy
      run: cargo clippy -- -A clippy::too-many-arguments -D warnings                                       
      
    - run: ./test.sh
    
  Build:
  
    runs-on: ubuntu-latest
      
    steps:
       #- name: Set default toolchain
         #run: rustup default stable
         
       - uses: actions/checkout@v3
       
       - run: ls -lha
         
       - name: Install Solana deps  
         run: sh -c "$(curl -sSfL https://release.solana.com/v1.10.25/install)"
         
       - name: Update source
         run: source ~/.bash_profile
          
       - name: Main Build
         run: cargo build-bpf
