name: Solana workflow

on:
 workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2
   
    steps:
    - uses: actions/checkout@v3
    
    - name: Set default toolchain
      run: rustup default stable
    
    - name: Formatting
      run: cargo fmt --all -- --check
    
    - name: Clippy
      run: cargo clippy -- -A clippy::too-many-arguments -D warnings              
      
    - name: Build BPF
      run: cargo build-bpf
      
    - name: Tests
      run: cargo test
      
